### ISSUE TITLE
Behavior icons no longer visible when selecting a node to add

### ISSUE THREAD

**Issue by Nsgr** [hpi-swa-lab/godot-pronto#121]
![grafik](https://github.com/hpi-swa-lab/godot-pronto/assets/28757333/d68d6f3a-c687-4a0e-ab4e-5a5a1086ed97)
Before the names of all behaviors were changed, the icons in this selection menu worked - now, everything just has the default node icon.

**Comment by tom95** [comment]
Probably just a hickup with the .godot cache. Please reopen if it cannot be fixed by clearing the cache.
