### ISSUE TITLE
Select number and "promote" to Value

### ISSUE THREAD

**Issue by tom95** [hpi-swa-lab/godot-pronto#146]
Introducing new tweakable values should be easier, for example by selecting a constant in code and hitting a button or shortcut to create a corresponding Value node nearby and replace the selected piece of code.

**Comment by tom95** [comment]
I think so, too. I believe the next-best thing would be to show a button next to our editors whenever there is a selection. (or maybe even always, if the layout will otherwise jump around too much)

**Comment by Finn-HPI** [comment]
I found a workaround for adding new items to the right-click menu (without proper documentation it was not really easy to find).
The feature currently supports the following data types:

- [ ] number (float, int)
- [ ] bool
- [ ] enum

I currently use the following Regex: ` ^\s*(([+-]?([0-9]*[.])?[0-9]+|true|false)(:([a-zA-Z0-9_]+))?)\s*$` to check for a valid text selections. This allows for the following Schema: `Value[:Name]?`. Here are some examples:

- `100.0` -> translated to `ValueBehavior<Float>` with name `Value#<timestamp>`
- `true` -> translated to` ValueBehavior<Bool>` with name `Value#<timestamp>`
- `-33.3:negative_float` -> translated to `ValueBehavior<Float> `with name `negative_float`
- `false:my_bool` -> translated to `ValueBehavior<Bool>` with name `my_bool`

There is a short-cut option `Shift+Ctrl+V`, which is displayed correctly but isn't working yet.
