### ISSUE TITLE
Prototyping UI - Save runtime values

### ISSUE THREAD

**Issue by JulianEgbert** [hpi-swa-lab/godot-pronto#157]
The Prototyping UI should have a button that allows to save the current runtime variable values in the editor inside the ValueBehaviors

**Comment by Finn-HPI** [comment]
I have made the following changes:

- During runtime of the game, if changes are made in the `PrototypingUI` the `ValueBehavior` objects are serialized as `Resources`.
- I have added a `synchronize button` to  the inspector of the `PrototypingUI`. Pressing it loads all saved `Resources` belonging to the currently present `ValueBehavior`s in the scene tree and updates their values.
