### ISSUE TITLE
Typing in an argument text box in the NodeToNodeConfigurator collapses its width

### ISSUE THREAD

**Issue by leogeier** [hpi-swa-lab/godot-pronto#159]
Possibly related to #78

**Comment by jgrenda** [comment]
![pronto_arg_resize_before](https://github.com/hpi-swa-lab/godot-pronto/assets/29424520/4b74beae-2a94-4ec6-8732-8cd470f1d23f)
Visual example of reproduction

**Comment by JulianEgbert** [comment]
This is also the case for other expression inputs (e.g. CodeBehavior)

**Comment by jgrenda** [comment]
![#159_fixed](https://github.com/hpi-swa-lab/godot-pronto/assets/29424520/799868ba-2c0b-4a54-802d-154fd14f6f2b)
fixed in #86565a2 and awaiting merge.
