### ISSUE TITLE
From, to, etc for conditionals

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-lab/godot-pronto#19]

**Comment by LinqLover** [comment]
Possible regression from 52359b584ac778662266fbbc6f60d330303a4c60

**Comment by LinqLover** [comment]
@Nsgr I tracked this regression down to b7cf81329def83a9345e8875cb8e975df38103a0 (the generated code for the condition no longer has a `return` statement), could you take a look at it? :)

**Comment by tom95** [comment]
@LinqLover The described problem was that `from` and `to` are not usable within conditions? Or that the change you linked constitutes a breaking change where the `return` now has to be explicitly placed before the condition?

I just confirmed that `from` and `to` should still be available. For the breaking change I believe we will keep this as-is for the moment being. With the previous mechanics prototypes being on separate branches, they should still be functioning and new prototypes should be built while keeping in mind that an explicit `return` is needed.

Automatically returning the only expression in a text field will be investigated separately, I just created #20 for that purpose.

**Comment by LinqLover** [comment]
@tom95 Oh, I'm sorry, I have mixed up both. I (and probably also another student during the class) was not aware that the `return` statement is also required within conditions (and there was no automatic migration, which would probably be out of scope). Yes, with `return` everything seems to work as before, I think this issue can be closed.
