### ISSUE TITLE
(Placeholder) Handles don't respect rotation

### ISSUE THREAD

**Issue by jgrenda** [hpi-swa-lab/godot-pronto#199]
When resizing a rotated placeholder the handles can't be used to achieve the desired result. The more often chosen workaround is deleting the placeholder, and fixing the shape without any rotation and possibly rotating afterwards. This is cumbersome.
![Recording 2023-12-02 at 13 19 37](https://github.com/hpi-swa-lab/godot-pronto/assets/29424520/f4f23b0d-0818-4b4e-8c8e-88106b1e1468)

**Comment by jgrenda** [comment]
The same applies to the connection symbol

**Comment by Finn-HPI** [comment]
Resizing is now working correctly for all Placeholder shapes, the problem with the connection symbol still open

**Comment by Finn-HPI** [comment]
The position and rotation of the connection symbol is now working correctly for all placeholder shapes.
