### ISSUE TITLE
Triggering triggers for StateMachineBehavior unsuccessful for different behaviors

### ISSUE THREAD

**Issue by jgrenda** [hpi-swa-lab/godot-pronto#207]
Currently calling the trigger method from a behavior through a connection does not work with all behaviors as expected.
While the functionality currently works when using the KeyBehavior, it does not when using e.g. an AlwaysBehavior, ControlsBehavior, or CollisionBehavior (others have not yet been tested).
This currently throws 2 errors:
![image](https://github.com/hpi-swa-lab/godot-pronto/assets/29424520/2fa116bb-3f6f-4638-b073-3c7c1bfe2c70)

Here is a recording of the setup used for replication:
![Recording 2024-01-25 at 17 06 12](https://github.com/hpi-swa-lab/godot-pronto/assets/29424520/63e83cbc-241b-484b-97cc-1e0a5da4fe7c)

Proposed solution: Make sure the trigger function of the StateMachineBehavior can be called through any connection from any behavior.

**Comment by jgrenda** [comment]
Tested on `Windows 10 22H2`, `Godot 4.2.1.stable` and 55777d.

**Comment by frcroth** [comment]
Should be fixed by #204
