### ISSUE TITLE
Query Behavior

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-lab/godot-pronto#31]

**Comment by LinqLover** [comment]
protocol/notes to myself:

- goals: find nodes in group, find nodes within distance/shape around parent, find nodes matching other criteria
- do not want to express queries as code, prefer higher-level properties in inspector
- prototype a couple of variants: what to do with the found nodes? return them as an array (pronto does not have a return mechanism), send each node back to requestor as a callback (context might be lost, provide it as another argument?), ...

**Comment by LinqLover** [comment]
# Design Thoughts

> **Note**
>
> **Legend:**
> - ⭐: chosen alternative
> - ❌: nay
> - ❶..❹: highest..lowest priority

## Use Cases

- bomb: destroy all players within a distance to the parent
- virus: copy/move an infectious node/property to the nearest/a random player [in a group] within a distance to the parent
- square sprinkler: set property on all fields within a rectangle around the parent

## Requirements

### Search Criteria

- none (all nodes)
- within a distance to parent (or another reference node) ❶
- in a group ❶
- is a class ❸
- within a shape ❷
  - select from list or from existing node?
    - cf. spawn shapes
    - choose what's easier to implement
- (has a property)
- (has a property with a value)
- (fulfills a closure predicate) ❷

### Selection Criteria

- number:
  - none (all nodes) ❶
  - top 1/top n ❶
- prioritization:
  - by distance ❶
  - by value of property
  - by result of closure
- random:
  - no random ❶
  - equal distribution [weighted by priority]

### Processing of Results

- control flow:
  - trigger signal for each result ⭐
  - trigger signal for entire results array ⭐
  - call closure for each result/results array
- context:
  - index
  - priority value
  - requestor
  - [request token (provided with query invocation)] ❸
- delay results each by x seconds? -> probably solved via #43 ❌

### Specification

- specification: query type (qualitative), arguments such as distance, group, closure, n (quantitative)
- intrinsic vs extrinsic arguments:
  - intrinsic: configure in inspector ⭐❶
    - pro: apter/more intuitive graphical configuration (documentation hints, more space, higher-level representations (e.g., node paths, group selection, value slider), combination of alternatives)
    - con: static for all uses of query
  - extrinsic: provide as arguments/select method
    - pro: dynamic configuration (e.g., bombs with different strengths, sprinklers with variable hydraulic pressure)
    - con: hard to express through code (limited space, limited documentation, ...)
  - combination: users can override certain properties extrinsically ❷
    - full argument list?
      - con: unused arguments take space
    - options argument?
      - con: no documentation/autocompletion
    - hardcoded list of arguments? ❌
      - con: not flexible, short-sighted design
    - offer method variants for all subsets?
      - con: very chaotic, bad maintainability
    - user-specified list of variable arguments? ⭐
      - user selects properties in inspector for overridability
        - checkbox for each argument? (`PROPERTY_USAGE_CHECKABLE`, but not self-explaining) ⭐
          - could insert an explanation above (as a read-only text or through a custom plugin)
        - array of strings?
        - support placeholder type for any argument?
          - Property list does not support type unions. we could use a custom EditorInspectorPlugin, but built-in inspector UI elements are not exposed through the API.
      - implementation: offer method variants with 0, 1, 2, ... generic arguments
      - pro: no wasted space, user knows what arguments are expected, flexible
      - con: cannot name arguments, higher UX complexity, higher implementation complexity
  - query types
    - types: spatial/behavioral
    - drop-down in inspector vs method name
    - i.e., should a query node be used for different types of queries?
      - probably not, since configurations would likely be heterogenous
    - pro method name: greater expressiveness
    - ⭐: drop-down in inspector
