### ISSUE TITLE
Level building: "drawing" a level

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-lab/godot-pronto#35]

**Comment by JulianEgbert** [comment]
Mabye a pre-configured TileMap would be a way to go since it allows to create large levels fairly easily. Cuurrrent downsides of TileMaps are the initial setup with setting hitboxes and coonfiguring tile size. If this could be done by a Behavior it would make using it very easy.

**Comment by JulianEgbert** [comment]
With the pre-configured TileMap this should be way easier now.
