### ISSUE TITLE
Prototyping UI shows wrong value for floats on loadup

### ISSUE THREAD

**Issue by JulianEgbert** [hpi-swa-lab/godot-pronto#36]
We have a float value initially set to `2.5` with stepsize `0.5`. However, when we start the game it shows a value of `3` inside the PrototypingUI (and this also seems to be the new value when the game has started). BUT we can still change the value with the slider to `2.5` during runtime.
Please try to fix this :)

**Comment by jgrenda** [comment]
Additionally we will add a toggle option for the UI

**Comment by janreppien** [comment]
closed by 5a73e41ed7ba36eb5a54f12467bc84b4584d7966
