### ISSUE TITLE
Awkward Code Dump

### ISSUE THREAD

**Issue by phkeese** [hpi-swa-lab/godot-pronto#37]
Add all your ideas as comments here

**Comment by phkeese** [comment]
**Goal:** Making something follow the mouse. 
**Workaround:** Always node which sets its parent's position to the global mouse position:
`to.global_position = to.get_global_mouse_position()`
**Idea:** Behavior `FollowMouse`

**Comment by tom95** [comment]
as we didn't end up using the collection, I'll close the issue. we'll have to instead source awkward code directly from the games or the changelogs.
