### ISSUE TITLE
Documenting all properties of Behaviors

### ISSUE THREAD

**Issue by tom95** [hpi-swa-lab/godot-pronto#50]
e.g., Spawner.scene_path

**Comment by LinqLover** [comment]
- alphabetize behaviors in readme

**Comment by LucPrestin** [comment]
Current state:

- [x] AlwaysBehavior
- [x] BackgroundBehavior
- [x] BindBehavior
- [x] CameraShakeBehavior
- [x] ClockBehavior
- [x] CodeBehavior
- [x] CollisionBehavior
- [x] ControlsBehavior
- [x] DragBehavior
- [x] GroupBehavior
- [x] HealthBarBehavior
- [ ] InspectBehavior
- [ ] InstanceBehavior
- [x] KeyBehavior
- [ ] MoveBehavior
- [x] NodeReadyBehavior
- [x] PlaceholderBehavior
- [ ] PlaceholderShapeBehavior
- [ ] PrototypingUIBehavior
- [x] SceneRootBehavior
- [x] SpawnerBehavior
- [x] StateBehavior
- [x] StateMachineBehavior
- [x] StopwatchBehavior
- [ ] ~~ValueBehavior~~
- [x] VisualLineBehavior
- [x] WatchBehavior
