### ISSUE TITLE
Bind behavior dependencies

### ISSUE THREAD

**Issue by tom95** [hpi-swa-lab/godot-pronto#7]
Two options:

1. We improve the way that the Prop resources are defined using a custom inspector. 
2. We drop explicit dependencies entirely because it's easier to type out in the convert expression anyways using G.at or get_node (no more awkward value0/value1). Downside: we can visualize less because all info is hidden in the expression.

**Comment by leogeier** [comment]
I like the first option for the potential of visualizations. Also, you would probably have to dig around less for properties in other nodes/behaviors.
