### ISSUE TITLE
Make emojis accessible for Placeholders

### ISSUE THREAD

**Issue by tom95** [hpi-swa-lab/godot-pronto#71]
* try out system fonts
* otherwise, try Noto from Google

**Comment by LinqLover** [comment]
What exactly is the issue here? We already used Unicode emojis successfully. Does it look weird on other platforms than Windows?

**Comment by tom95** [comment]
Color emojis seem not to be displayed in-game. However, I think with the sprite library we already have a pretty good standing, so I'll close this issue as out-of-scope for the moment.
