### ISSUE TITLE
Way to pause the game but still process signals

### ISSUE THREAD

**Issue by phkeese** [hpi-swa-lab/godot-pronto#75]
Potential use cases would be to show some UI to explain a side effect without having to manage pause-state in all other behaviors.

Maybe something like an "pausable" attribute on connections which blocks them from firing/queues the event until pause mode is restored to realtime?

**Comment by jgrenda** [comment]
Godot base functionalities [get_tree().paused](https://docs.godotengine.org/en/stable/tutorials/scripting/pausing_games.html) should be able to do all this.
Nodes have a processing mode which is inherited by default.
What benefit would a pausable attribute actually bring to the table?

![image](https://github.com/hpi-swa-lab/godot-pronto/assets/29424520/0d560aec-5abe-47c5-92f0-bbc7282aedce)

**Comment by tom95** [comment]
I just made sure that Key and Controls are respecting the process_mode=PAUSE setting but would agree with @jgrenda that we should probably not duplicate that field from Godot's defaults
