### ISSUE TITLE
Font size in code editor is fixed

### ISSUE THREAD

**Issue by phkeese** [hpi-swa-lab/godot-pronto#80]
I would like to be able to increase the font-size of code editors like in other IDEs.
This setting should be local-only, maybe in a separate config-file e.g. `.prontorc`.

**Comment by tom95** [comment]
I would argue as a "won't fix" here... Pronto already respects the global text editor setting. I would say if you need larger text in one of the argument panels the recommended way to go is to open it in the full text editor.

Please do tell if that doesn't sound feasible :)
