### ISSUE TITLE
Cannot use `await` in connections

### ISSUE THREAD

**Issue by phkeese** [hpi-swa-lab/godot-pronto#97]
Allowing asynchronous code would allow for greater flexibility

**Comment by LinqLover** [comment]
Workaround: use the await in a deferred lambda call

**Comment by tom95** [comment]
So the godot docs suggest that await'ing a value that is not a coroutine will not impact execution in anyway. As such, it seems like we can just sprinkle await everywhere and then await in scripts works, too. 

https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#awaiting-for-signals-or-coroutines
